export const CHANGE_UNITS = 'CHANGE_UNITS'
export const CHANGE_ZIPCODE = 'CHANGE_ZIPCODE'
export const FETCH_CURRENT_WEATHER_BY_ZIPCODE_SUCCESS =
    'FETCH_CURRENT_WEATHER_BY_ZIPCODE_SUCCESS'
export const FETCH_FORECAST_BY_ZIPCODE_SUCCESS =
    'FETCH_FORECAST_BY_ZIPCODE_SUCCESS'
export const FETCH_CURRENT_WEATHER_AND_FORECAST_BY_LAT_LON_SUCCESS =
    'FETCH_CURRENT_WEATHER_AND_FORECAST_BY_LAT_LON_SUCCESS'
export const FETCH_FAIL = 'FETCH_FAIL'
